#!/bin/sh

# Edit the format if you want a different citation marker
CAYW_URL="http://localhost:23119/better-bibtex/cayw?format=pandoc"

BBT_status=$(/usr/bin/curl 'http://localhost:23119/better-bibtex/cayw?probe=probe' 2>/dev/null)

if [ "$BBT_status" == "ready" ] 2>/dev/null; then
		notify-send "Accessing Zotero picker..."
		citation=$(/usr/bin/curl $CAYW_URL 2>/dev/null)
		echo $citation | xclip -sel clip 
		exit 0;

elif [ -z "$BBT_status" ]; then
		notify-send "Please launch Zotero with the Better BibTeX plugin. If Zotero is running, check 'Enable export by HTTP' in BBT and restart Zotero."
		exit 4;

elif [ "$BBT_status" == "No endpoint found" ] 2>/dev/null; then
		notify-send "Better BibTeX cannot find your library. Ensure only one Zotero instance is open. If so, reinstall Better BibTeX."
else
		notify-send "Unknown error in Better BibTex. Please restart Zotero and try again."
fi
exit 5;
